spring:
  application:
    name: pathwise
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-square-sea-azzex9dm.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_LxHQ0YvgVXq4}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security: 
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:mock-client-id}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:mock-client-secret}
            scope: email, profile

jwt:
  secret: ${JWT_SECRET:pathwise_super_secret_jwt_key_that_is_at_least_32_bytes_long_123456789}
  expiration-ms: 3600000
  refresh-expiration-ms: 86400000

ai:
  gemini:
    api-key: ${GEMINI_API_KEY:}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}

server:
  port: 4444
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
